Booking_MS/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^booking/', include('booking.urls')),
]

booking/urls.py
#!/usr/bin/env python3.5
# -*- coding: utf-8 -*-
# @Time    : 17-12-7 下午4:48
# @Author  : 无敌小龙虾
# @File    : urls.py.py
# @Software: PyCharm


from django.conf.urls import url
from . import views

app_name = 'booking'

urlpatterns = [
    url(r'^$', views.IndexView, name='index'),
    url(r'^register/$', views.Register, name='register'),
    url(r'^login/$', views.Login, name='login'),
    url(r'^logout/$', views.Logout, name='logout'),
    url(r'^detail/$', views.DetailView, name='detail'),
    url(r'^book/$', views.Booking, name='book'),
    url(r'^result/$', views.resultView, name='result'),
    # url(r'^count/$', views.statisticView, name='statistic'),
    url(r'^count/department/$',views.DstatisView, name='dstatis'),
    url(r'^count/magazine/$', views.MstatisView, name='mstatis'),
    url(r'^count/person/$', views.PstatisView, name='pstatis')
]

booking/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


# Create your models here.

class Department(models.Model):
    depart_name = models.CharField(max_length=20)
    depart_num = models.CharField(max_length=10)

    def __str__(self):
        return self.depart_name


class Staff(models.Model):
    staff_name = models.CharField(max_length=20)
    staff_number = models.CharField(max_length=20)
    mobile = models.CharField(max_length=20)
    password = models.CharField(max_length=100, default='123456')
    department = models.ForeignKey(Department, on_delete=models.CASCADE)

    def __str__(self):
        return self.staff_name


class Magazines(models.Model):
    staff = models.ManyToManyField(Staff, blank=True)
    mag_name = models.CharField(max_length=20)
    price = models.FloatField()
    comment = models.TextField(max_length=200, default='', blank=True)
    number = models.CharField(max_length=10)

    def __str__(self):
        return self.mag_name

booking/views.py
from django.shortcuts import render, redirect

from .models import Magazines, Staff, Department


# Create your views here
# .

def is_login(request):
    return request.session.get('islogin', False)


def user_name(request):
    return request.session.get('username')


def user_pricecount(request):
    return request.session.get('pricecount')


def user_id(request):
    return request.session.get('userid', -1)


def IndexView(request):
    # magazine_list = Magazines.objects.all()
    islogin = is_login(request)
    username = user_name(request)
    context = {
        # 'magazine_list': magazine_list,
        'islogin': islogin,
        'username': username
    }

    return render(request, 'booking/index.html', context)


'''
报刊信息
'''


def DetailView(request):
    magazine_list = Magazines.objects.all()
    islogin = is_login(request)
    username = user_name(request)
    context = {
        'magazine_list': magazine_list,
        'username': username,
        'islogin': islogin
    }
    return render(request, 'booking/detail.html', context)


'''
登录操作
'''


def Login(request):
    username = ''
    password = ''
    try:
        username = request.POST['username']
        password = request.POST['password']
        is_post = True

    except KeyError:
        is_post = False

    if is_post:
        _state = do_login(request, username, password)

        if _state['success']:
            return redirect('booking:index')

    else:
        _state = {
            'success': False,
            'message': ""
        }

    _result = {
        'success': _state['success'],
        'message': _state['message']
    }

    return render(request, 'booking/login.html', _result)


def do_login(request, username, password):
    _state = check_login(username, password)

    if _state['success']:
        request.session['islogin'] = True,
        request.session['userid'] = _state['userid']
        request.session['username'] = username
        request.session['pricecount'] = 0
    return _state


def check_login(username, password):
    _state = {
        'success': True,
        'message': 'none',
        'userid': -1,
    }

    try:
        user = Staff.objects.get(staff_name=username)

        if password == user.password:
            _state['success'] = True
            _state['userid'] = user.id

        else:
            _state['success'] = False
            _state['message'] = '密码错误.'

    except Staff.DoesNotExist:
        _state['success'] = False
        _state['message'] = "不存在此账户"

    return _state


def Logout(request):
    request.session['islogin'] = False
    request.session['userid'] = -1
    request.session['username'] = ''
    return redirect('booking:index')


"""
注册操作
"""


def Register(request):
    islogin = is_login(request)

    if islogin:
        return redirect('booking:index')

    userinfo = {
        'staff_name': '',
        'password': '',
        'comfirm': '',
        'mobile': '',
        'department': '',
        'staff_number': '',
    }

    try:
        userinfo = {
            'staff_name': request.POST['staff_name'],
            'password': request.POST['password'],
            'comfirm': request.POST['comfirm'],
            'mobile': request.POST['mobile'],
            'department': request.POST['department'],
            'staff_number': request.POST['staff_number'],
        }

        _is_post = True

    except KeyError:
        _is_post = False

    if _is_post:
        _state = do_register(request, userinfo)

    else:
        _state = {
            'success': False,
            'message': '',
        }

    if _state['success']:
        return redirect('booking:index')

    _result = {
        'success': _state['success'],
        'message': _state['message'],
        'form': {
            'staff_name': userinfo['staff_name'],
        }
    }

    return render(request, 'booking/register.html', _result)


def do_register(request, userinfo):
    _state = {
        'success': False,
        'message': '',
    }

    if userinfo['staff_name'] == '':
        _state['success'] = False
        _state['message'] = '没有输入用户名.'
        return _state

    if userinfo['password'] == '':
        _state['success'] = False
        _state['message'] = '没有输入密码.'
        return _state

    if userinfo['department'] == '':
        _state['success'] = False
        _state['message'] = '没有输入所在部门.'
        return _state

    if userinfo['staff_number'] == '':
        _state['success'] = False
        _state['message'] = '没有输入员工号.'
        return _state

    if userinfo['mobile'] == '':
        _state['success'] = False
        _state['message'] = '没有输入电话号码.'
        return _state

    if userinfo['password'] != userinfo['comfirm']:
        _state['success'] = False
        _state['message'] = '两次密码不匹配'
        return _state

    staff = Staff(
        staff_name=userinfo['staff_name'],
        password=userinfo['password'],
        staff_number=userinfo['staff_number'],
        mobile=userinfo['mobile'],
        department=Department.objects.get(depart_name=userinfo['department'])
    )

    staff.save()
    return _state


'''
订阅操作

'''


def Booking(request):
    islogin = is_login(request)
    pricecount = user_pricecount(request)

    if not islogin:
        return redirect('booking:login')

    userid = user_id(request)
    try:
        user = Staff.objects.get(id=userid)
        username = user_name(request)

    except:
        return redirect('booking:login')

    try:
        magid = request.POST['mag']
        magzine = Magazines.objects.get(id=magid)
        print(magid)

    except KeyError:
        return redirect('booking:detail')

    else:
        if check_boking(username, magzine):
            magzine.staff.add(user)
            pricecount += magzine.price
            request.session['pricecount'] = pricecount
            return resultView(request,
                              ('你已成功预定%s,价格为%s., 此次登录预定一共花%s元钱.') % (magzine.mag_name, magzine.price, pricecount))
        else:
            return resultView(request, '对不起,你已经预订了此报刊,不能再次预订')


# 检查有没有预定
def check_boking(username, magzine):
    _exit = True
    try:
        magzine.staff.get(staff_name=username)
        _exit = False
    except:
        _exit = True
    return _exit


def resultView(request, message=''):
    islogin = is_login(request)
    username = user_name(request)

    context = {
        'islogin': islogin,
        'message': message,
        'username': username
    }

    return render(request, 'booking/result.html', context)


'''
信息统计显示部分
'''


def DstatisView(request):
    islogin = is_login(request)

    if not islogin:
        return redirect('booking:login')
    username = user_name(request)

    d_list = Department.objects.all()

    context = {
        'd_list': d_list,
        'islogin': islogin,
        'username': username
    }

    return render(request, 'booking/statisdetail.html', context)


def MstatisView(request):
    islogin = is_login(request)

    username = user_name(request)

    mag_list = Magazines.objects.all()

    context = {
        'mag_list': mag_list,
        'islogin': islogin,
        'username': username
    }

    return render(request, 'booking/statisdetail.html', context)


def PstatisView(request):
    islogin = is_login(request)

    if not islogin:
        return redirect('booking:login')

    username = user_name(request)

    person = Staff.objects.get(staff_name=username)

    context = {
        'person': person,
        'islogin': islogin,
        'username': username
    }

    return render(request, 'booking/statisdetail.html', context)

booking/templates/booking/base.html
<!DOCTYPE html>
<!-- booking/templates/booking/base.html -->

{% load static %}
<html>
<head>
  <meta charset="utf-8">
  <title>报刊订阅</title>
  <link rel="stylesheet" href="{% static 'booking/css/semantic.css' %}">
</head>

<body>
  <div class="ui inverted fixed fitted borderless fluid five item menu">
    <a href="{% url 'booking:index' %}" class="item">首页</a>
    <a href="{% url 'booking:detail' %}" class="item">报刊信息</a>
    <a href="{% url 'booking:dstatis' %}" class="item">订阅信息</a>
      {% if islogin %}
          <a href="#" class="item">Hello,{{ username }}</a>
          <a href="{% url 'booking:logout' %}" class="item"><i class="sign out icon"></i>注销</a>

      {% else %}
          <a href=" {% url 'booking:register' %}" class="item">
            <i class="share icon"
            ></i>
            注册
            </a>
        <a href="{% url 'booking:login' %}" class="item">
          登录
          <i class="sign in icon"></i>
        </a>

      {% endif %}
  </div>


  <div class="ui  vertical secondary basic segment">
    <div class="ui banner image">
      <img src="{% static 'booking/images/banner.jpg' %}" alt="">
    </div>

  </div>

  <div class="ui container segment" id="content">
      {% block content %} {% endblock %}
  </div>

  <div class="ui inverted  vertical very padded  segment">
              John®
  </div>

</body>

</html>

booking/templates/booking/countmessage.html
{% extends 'booking/base.html' %}

{% block content %}
      <div class="ui vertical  secondary basic segment">
    <div class="ui inverted three  item menu">
      <a href="{% url 'booking:dstatis' %}" class="item">部门</a>
      <a href="{% url 'booking:mstatis' %}" class="item">报刊</a>
      <a href="{% url 'booking:pstatis' %}" class="item">个人</a>
    </div>

    <div class="ui container very padded segment">
        {% block main %}

        {% endblock %}

      </div>

    </div>

{% endblock %}

booking/templates/booking/detail.html
{% extends 'booking/base.html' %}

{% block content %}
    <form action="{% url 'booking:book' %}" method="post">
    {% csrf_token %}
    <div class="ui vertical secondary very padded segment">
        <div class="ui container">
            {% if magazine_list %}
            <div class="ui three stackable cards">
                {% for mag in magazine_list %}
                 <div class="card">
                    <div class="content">

                         <div class="header">
                             {{ mag.mag_name }}
                         </div>

                        <div class="ui divider"></div>

                        <div class="dersciption">
                            {{ mag.comment }}
                         </div>

                        <button class="fluid ui  bottom attached animated fade button" name="mag"
                        value="{{ mag.id }}">

                            <div class="visible content">
                            <i class="shop icon"></i>订阅
                            </div>
                            
                            <div class="hidden content">
                                <i class="yen icon"></i>
                            {{ mag.price }}/年
                            </div>

                        </button>

                     </div>
                </div>
            {% endfor %}
            </div>
            {% endif %}
        </div>
    </div>
    </form>

{% endblock %}

booking/templates/booking/index.html
{% extends 'booking/base.html' %}
{% load static %}


{% block content %}
    <div class="ui vertical secondary basic segment">
    <div class="ui container">
      <div class="ui center aligned teal header">
        Hello,欢迎来到报刊订阅系统
      </div>

    </div>
    <div class="ui fitted three item  menu">
      <div class="ui image">
        <img src="{% static 'booking/images/book1.jpg' %}" alt="">
      </div>

      <div class="ui image">
        <img src="{% static 'booking/images/book2.jpg' %}" alt="">
      </div>

      <div class="ui image">
        <img src="{% static 'booking/images/book3.jpg' %}" alt="">
      </div>
    </div>
  </div>

  <div class="ui vertical secondary basic segment">
    <div class="ui container segment">
      <p><strong>阅读，这是最好的学问。</strong>
      </p>

    </div>
  </div>


{% endblock %}

booking/templates/booking/login.html
<!DOCTYPE html>
{% load static %}
<html>
  <head>
    <meta charset="utf-8">
    <title>登录</title>

    <link rel="stylesheet" href="{% static 'booking/css/semantic.css' %}">
    <style type="text/css">
      body {
        background-color: #DADADA;
      }

      body>.grid {
        height: 100%;
      }
      .column {
        max-width: 450px;
      }
    </style>
  </head>
  <body>
    <div class="ui middle aligned center aligned grid">
      <div class="column">
        <h2 class="ui teal header">
          <div class="content">
            登录
          </div>
        </h2>
          <div class="message">{{ message }}</div>
        <form class="ui large form" action="{% url 'booking:login' %}" method="post">
             {% csrf_token %}
          <div class="ui stacked segment">
            <div class="field">
              <div class="ui left icon input">
                <i class="user icon"></i>
                <input type="text" name="username" placeholder="用户名">
              </div>
            </div>

            <div class="field">
              <div class="ui left icon input">
                <i class="barcode icon"></i>
                <input type="password" name="password" placeholder="密码">
              </div>
            </div>

            <button class="ui fluid large blue submit button ">
              Login
            </button>

          </div>
        </form>

          <div class="ui message">
            <div class="ui segment">
              <a href="{% url 'booking:register' %}">注册</a>
            </div>

            <div class="ui segment">
              <i class="home icon"></i>
              <a href="{% url 'booking:index' %}">返回主页</a>
            </div>
          </div>

      </div>
    </div>

  </body>
</html>

booking/templates/booking/register.html
<!DOCTYPE html>

{% load static %}
<html>

<head>
  <meta charset="utf-8">
  <title>注册</title>
  <link rel="stylesheet" href="{% static 'booking/css/semantic.css' %}">
  <style type="text/css">
    body {
      background-color: #DADADA;
    }

    body>.grid {
      height: 100%;
    }

    .column {
      max-width: 450px;
    }
  </style>
</head>

<body>
  <div class="ui middle aligned center aligned grid">
    <div class="column">
      <h2 class="ui teal header">
        <div class="content">
          注册
        </div>
      </h2>
        <div class="message">{{ message }}</div>
      <form class="ui large form" action="{% url 'booking:register' %}" method="post">
          {% csrf_token %}
        <div class="ui stacked segment">
          <div class="field">
            <div class="ui left icon input">
              <i class="user icon"></i>
              <input type="text" name="staff_name" placeholder="用户名" value="{{ state.form.staff_name }}">
            </div>
          </div>

          <div class="field">
            <div class="ui left icon input">
              <i class="world icon"></i>
              <input type="text" name="department" placeholder="部门" value="{{ state.form.department}}">
            </div>
          </div>


          <div class="field">
            <div class="ui left icon input">
              <i class="barcode icon"></i>
              <input type="text" name="staff_number" placeholder="员工号"  value="{{ state.form.staff_number }}">
            </div>
          </div>


            <div class="field">
            <div class="ui left icon input">
              <i class="barcode icon"></i>
              <input type="text" name="mobile" placeholder="电话"  value="{{ state.form.mobile }}">
            </div>
          </div>

          <div class="field">
            <div class="ui left icon input">
              <i class="barcode icon"></i>
              <input type="password" name="password" placeholder="密码">
            </div>
          </div>


          <div class="field">
            <div class="ui left icon input">
              <i class="barcode icon"></i>
              <input type="password" name="comfirm" placeholder="确认密码">
            </div>
          </div>


          <button class="ui fluid large blue submit button " >
            Register
          </button>

        </div>
      </form>

        <div class="ui message">
          <div class="ui segment">
            <a href="{% url 'booking:login' %}">用已有账号登录</a>
          </div>
          <div class="ui segment">
            <i class="home icon"></i>
            <a href="{% url 'booking:index' %}">
              返回首页
            </a>
          </div>

        </div>

    </div>
  </div>

</body>

</html>

booking/templates/booking/result.html
{% extends 'booking/base.html' %}

{% block content %}

    <div class="ui vertical secondary very padded segment">
        <div class="ui positive big message">
            <div class="header">
                {{ message }}
            </div>
        </div>
    <a class="ui right floated black basic button" href="{% url 'booking:detail' %}">再次预定</a>
    </div>
{% endblock %}

booking/templates/booking/statisdetail.html
{% extends 'booking/countmessage.html' %}

{% block main %}
    {% if d_list %}
    {% for d in d_list %}
        <div class="ui container segment">
                <h4>
                    {{ d.depart_name }}
                </h4>
        <div class="ui divider"></div>
            {% for staff in d.staff_set.all %}

                <h5>{{ staff.staff_name }}</h5>

                <div class="ui right floated  statistic">
                    <div class="value">
                        {{ staff.magazines_set.all | length }}
                    </div>
                    <div class="label">订阅</div>
                </div>

                <div class="ui divider"></div>
                 {% for m in staff.magazines_set.all  %}

                     <p>{{ m.mag_name }} </p>

                 {% endfor %}

                {% endfor %}
        </div>
    {% endfor %}

     {% endif %}

     {% if mag_list %}
        {% for mag in mag_list %}
            <div class="ui container segment">
                <h4> {{ mag.mag_name }}</h4>
             <div class="ui right floated  statistic">
                    <div class="value">
                        {{ mag.staff.all | length }}
                    </div>
                    <div class="label">订阅</div>
                </div>

            <div class="ui divider"></div>
            {% for p in mag.staff.all %}
                <p>{{ p.staff_name }}</p>

                {% endfor %}

            </div>

        {% endfor %}

    {% endif %}


    {% if person %}
        <div class="ui container segment">
        <h4>{{ person.staff_name }}</h4>

        <div class="ui right floated statistic">
            <div class="value">
                {{ person.magazines_set.all | length }}
            </div>

            <div class="label">订阅</div>

        </div>

        <div class="ui divider"></div>
        {% for mag in person.magazines_set.all %}
            <p>{{ mag.mag_name }}</p>

        {% endfor %}
        </div>
    {% endif %}



{% endblock %}